export const SET_ALL_RESOURCE_ATTRS = 'SET_ALL_RESOURCE_ATTRS'
export const SET_SYS_NAME = 'SET_SYS_NAME'
export const SET_PLATFORM = 'SET_PLATFORM'
export const SET_CAR_SHOW = 'SET_CAR_SHOW'
export const SET_CLOUD_PROVIDER_STEP = 'SET_CLOUD_PROVIDER_STEP'
export const SET_METADATA = 'SET_METADATA'
export const UPDATE_METADATA = 'UPDATE_METADATA'
export const DELETE_METADATA = 'DELETE_METADATA'
export const SET_NAVBAR_DISPLAY = 'SET_NAVBAR_DISPLAY'
export const SET_INSTANCE_CONFIG = 'SET_INSTANCE_CONFIG'
export const SET_CHECKED_METADATA = 'SET_CHECKED_METADATA'
export const SET_GROUP_ACTIONS = 'SET_GROUP_ACTIONS'
export const SET_BASIC_DETAIL_GROUP = 'SET_BASIC_DETAIL_GROUP'
export const SET_CHECKED_INSTANCE_ID = 'SET_CHECKED_INSTANCE_ID'
export const SET_OPERATOR_SUCCESS = 'SET_OPERATOR_SUCCESS'
/**
 * 控制台 保存当前所选实例的基本信息
 * @type [Object]
 */
export const SET_INSTANCE_INFO = 'SET_INSTANCE_INFO'

/**
 * 资源池 保存当前选中资源数据
 * @type {string}
 */
export const SET_SOURCE_POOL_CUR_SELECTED = 'SET_SOURCE_POOL_CUR_SELECTED'
/**
 * 资源池 重置当前选中资源数据
 * @type {string}
 */
export const CLEAR_SOURCE_POOL_CUR_SELECTED = 'CLEAR_SOURCE_POOL_CUR_SELECTED'
/**
 * 成本分析 保存当前选中过滤条件
 * @type {string}
 */
export const SET_COST_DETAIL_FILTER = 'SET_COST_DETAIL_FILTER'
export const SET_UCMP_NAV_LIST = 'SET_UCMP_NAV_LIST'
export const SET_ACTIVED_NAV_INDEX = 'SET_ACTIVED_NAV_INDEX'
/**
 * @description 添加购物车信息
 * @type {string}
 */
export const ADD_SHOP_CAR = 'ADD_SHOP_CAR'
/**
 * @description 删除购物车信息
 * @type {string}
 */
export const DELETE_SHOP_CAR = 'DELETE_SHOP_CAR'
export const SET_CHECKED_PROVIDER_ID = 'SET_CHECKED_PROVIDER_ID'
// 用户自定义 控制台显示列
export const SET_CUSTOM_CONFIG_CONSOLE_TABLE_COLS = 'SET_CUSTOM_CONFIG_CONSOLE_TABLE_COLS'
// 全局参数 资源所属
export const SET_GLOBAL_PARAM_RESOURCE_BELONG = 'SET_GLOBAL_PARAM_RESOURCE_BELONG'
// 全局参数 租期设置
export const SET_GLOBAL_PARAM_TENANCY = 'SET_GLOBAL_PARAM_TENANCY'
// 全局参数 nas自动挂载
export const SET_GLOBAL_PARAM_NAS_AUTO_ATTACH = 'SET_GLOBAL_PARAM_NAS_AUTO_ATTACH'
// 全局参数 申请资源是否上传附件
export const SET_GLOBAL_PARAM_ATTACHMENT = 'SET_GLOBAL_PARAM_ATTACHMENT'
// 全局参数 申请资源是否显示业务
export const SET_GLOBAL_PARAM_BUSINESS = 'SET_GLOBAL_PARAM_BUSINESS'
// 全局参数 回收站设置
export const SET_GLOBAL_PARAM_RECYCLE = 'SET_GLOBAL_PARAM_RECYCLE'
// 全局参数 优先级
export const SET_ORDER_LEVEL_DISPLAY = 'SET_ORDER_LEVEL_DISPLAY'
// 全局参数 系统参数设置
export const SET_GLOBAL_PARAM_SYSTEM = 'SET_GLOBAL_PARAM_SYSTEM'

// 监控告警
// ***告警策略
// -- 监控对象类型
export const SET_MONITOR_RESOURCE_MAP = 'SET_MONITOR_RESOURCE_MAP'
export const SET_MONITOR_RESOURCE_METRIC_MAP = 'SET_MONITOR_RESOURCE_METRIC_MAP'
export const SET_MONITOR_RESOURCE_METRIC_MAP_ITEM = 'SET_MONITOR_RESOURCE_METRIC_MAP_ITEM'
export const SET_FORM_DATA_AND_DISPLAY = 'SET_FORM_DATA_AND_DISPLAY'
export const SET_BP_RESOURCES = 'SET_BP_RESOURCES'
export const SET_BP_DEPENDENCIES = 'SET_BP_DEPENDENCIES'
export const SET_BP_FORM = 'SET_BP_FORM'
// 总览-过滤参数
export const SET_DASHBOARD_FILTER = 'SET_DASHBOARD_FILTER'
// 工单-全局参数获取
export const SET_GLOBAL_PARAM_WORKSHEET = 'SET_GLOBAL_PARAM_WORKSHEET'
export const SET_WORKSHEET_ROLE_LIST = 'SET_WORKSHEET_ROLE_LIST' // 工单-角色列表获取
export const SET_USER_ROLE = 'SET_USER_ROLE' // 工单-用户角色获取
// 台账-云厂商
export const SET_REPORT_PROVIDER = 'SET_REPORT_PROVIDER'
export const SET_REPORT_PROVIDER_READY = 'SET_REPORT_PROVIDER_READY'
export const SET_REPORT_PROVIDER_DEFAULT = 'SET_REPORT_PROVIDER_DEFAULT'
// 自定义大屏
export const SET_BIG_SCREEN_URL = 'SET_BIG_SCREEN_URL'
export const SET_METADATA_APPLY_PRIVILEGES = 'SET_METADATA_APPLY_PRIVILEGES'
export const SET_MENU_METADATA_PROMISE = 'SET_MENU_METADATA_PROMISE'

export const SET_BUSINESSORPROJECT_TYPE = 'SET_BUSINESSORPROJECT_TYPE'
export const SET_PHYSICAL_INSTANCE_INFO = 'SET_PHYSICAL_INSTANCE_INFO'
